name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo_mysql, bcmath

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up .env for Testing with SQLite
        run: |
          cp .env.testing .env
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env
          sed -i 's/DB_DATABASE=homestead/DB_DATABASE=:memory:/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=/' .env
          sed -i 's/APP_ENV=production/APP_ENV=testing/' .env
          echo "DB_CONNECTION=sqlite" >> .env.testing
          echo "DB_DATABASE=:memory:" >> .env.testing
          echo "APP_ENV=testing" >> .env.testing

      - name: Run Migrations
        run: php artisan migrate --env=testing --force

      - name: Seed Database
        run: php artisan db:seed --env=testing

      - name: Run Tests
        run: php artisan test --env=testing
