name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  development:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: ci_cd_test
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo_mysql, bcmath

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up .env for Development
        run: |
          cp .env.example .env
          sed -i 's/DB_DATABASE=homestead/DB_DATABASE=ci_cd_test/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=test_user/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=test_password/' .env

      - name: Wait for MySQL
        run: |
          for i in {1..15}; do
            if mysqladmin ping -hmysql -uroot -ptest_password --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Migrations
        run: php artisan migrate --env=development --force

      - name: Seed Database
        run: php artisan db:seed --env=development

      - name: Run Tests
        run: php artisan test --env=development
