name: userone

on:
  push:
    branches:
      - master  # Or your default branch
  pull_request:
    branches:
      - master  # Or your default branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: userone@gmail
          MYSQL_DATABASE: userone
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host 127.0.0.1 --password=secret"
          --health-timeout=30s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Or the version you need for your Laravel application
          extensions: mbstring, pdo, pdo_mysql, bcmath, xml
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up .env file
        run: |
          cp .env.testing .env
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=homestead/DB_DATABASE=test_database/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=secret/' .env

      - name: Run database migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test --env=testing
