name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up PHP
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'

    # Step 2: Checkout code
    - uses: actions/checkout@v4

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Step 4: Set up MySQL
    - name: Setup MySQL
      uses: actions/setup-mysql@v2
      with:
        mysql-version: '8.0' # Specify your desired MySQL version
        database: userone
        username: userone
        password: userone@gmail

    # Step 5: Run migrations
    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: userone
        DB_USERNAME: userone
        DB_PASSWORD: userone@gmail
      run: php artisan migrate --force

    # Step 6: Generate application key
    - name: Generate key
      run: php artisan key:generate

    # Step 7: Set directory permissions
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Step 8: Start Laravel server
    - name: Start Laravel server
      run: php artisan serve --host=0.0.0.0 --port=8000 &
      env:
        APP_ENV: testing

    # Step 9: Wait for server to start
    - name: Wait for server to start
      run: sleep 10

    # Step 10: Test application endpoints
    - name: Test application endpoints
      run: |
        curl -s http://127.0.0.1:8000 | grep "Laravel" || exit 1
        curl -s http://127.0.0.1:8000/another-endpoint | grep "Expected Content" || exit 1

    # Step 11: Execute PHPUnit or Pest tests
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: userone
        DB_USERNAME: userone
        DB_PASSWORD: userone@gmail
      run: php artisan test
