name: CI/CD Pipeline

on:
  push:
    branches:
      - master     # Production deployment
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  # Development Stage
  development:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ptnduj95jq8h3r3l
          MYSQL_DATABASE: arnzsrctr6a41zuj
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=30s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_mysql, bcmath, xml

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up .env for Development
        run: |
          cp .env.example .env
          sed -i 's/APP_ENV=production/APP_ENV=development/' .env
          sed -i 's/APP_DEBUG=false/APP_DEBUG=true/' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/' .env
          sed -i 's/DB_DATABASE=homestead/DB_DATABASE=arnzsrctr6a41zuj/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=ptnduj95jq8h3r3l/' .env

      - name: Wait for MySQL
        run: |
          for i in {1..15}; do
            if mysqladmin ping -hmysql -uroot -pptnduj95jq8h3r3l --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Test MySQL Connectivity
        run: |
          mysql -hmysql -uroot -pptnduj95jq8h3r3l -e "SHOW DATABASES;"

      - name: Run Migrations and Seeders
        run: php artisan migrate --force --seed

      - name: Run Tests
        run: php artisan test --env=development

      - name: Deploy Application
        run: echo "Production deployment steps here!"
