name: CI/CI pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Change to your required PHP version
        extensions: mbstring, intl, bcmath

    # Install dependencies
    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist
